apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-db-pv
  labels:
    type: local
    app: audit-db
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/audit-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-db-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
