apiVersion: v1
kind: PersistentVolume
metadata:
  name: customer-db-pv
  labels:
    type: local
    app: customer-db
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/customer-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-db-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
