apiVersion: v1
kind: PersistentVolume
metadata:
  name: employee-db-pv
  labels:
    type: local
    app: employee-db
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/employee-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: employee-db-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
