apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-db-pv
  labels:
    type: local
    app: inventory-db
spec:
  storageClassName: standard
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/inventory-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-db-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
