apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  # Customer DB credentials (base64 encoded)
  CUSTOMER_DB_USER: Y3VzdG9tZXJfdXNlcg==  # customer_user
  CUSTOMER_DB_PASSWORD: Y3VzdG9tZXJfcGFzcw==  # customer_pass
  CUSTOMER_DB_NAME: Y3VzdG9tZXJfZGI=  # customer_db
  
  # Employee DB credentials
  EMPLOYEE_DB_USER: ZW1wbG95ZWVfdXNlcg==  # employee_user
  EMPLOYEE_DB_PASSWORD: ZW1wbG95ZWVfcGFzcw==  # employee_pass
  EMPLOYEE_DB_NAME: ZW1wbG95ZWVfZGI=  # employee_db
  
  # Inventory DB credentials
  INVENTORY_DB_USER: aW52ZW50b3J5X3VzZXI=  # inventory_user
  INVENTORY_DB_PASSWORD: aW52ZW50b3J5X3Bhc3M=  # inventory_pass
  INVENTORY_DB_NAME: aW52ZW50b3J5X2Ri  # inventory_db
  
  # Audit DB credentials
  AUDIT_DB_USER: YXVkaXRfdXNlcg==  # audit_user
  AUDIT_DB_PASSWORD: YXVkaXRfcGFzcw==  # audit_pass
  AUDIT_DB_NAME: YXVkaXRfZGI=  # audit_db
  
  # Aggregated DB credentials
  AGGREGATED_DB_USER: YWdncmVnYXRlZF91c2Vy  # aggregated_user
  AGGREGATED_DB_PASSWORD: YWdncmVnYXRlZF9wYXNz  # aggregated_pass
  AGGREGATED_DB_NAME: YWdncmVnYXRlZF9kYg==  # aggregated_db
  
  # Redis credentials
  REDIS_PASSWORD: cmVkaXNfcGFzcw==  # redis_pass
  
  # JWT Secret
  JWT_SECRET: c2VjcmV0X2tleV9mb3Jfand0X3Rva2Vucw==  # secret_key_for_jwt_tokens
