apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: danacore/inventory-service:latest
        ports:
        - containerPort: 31003
        resources:
          limits:
            cpu: "800m"
            memory: "768Mi"
          requests:
            cpu: "400m"
            memory: "384Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        - name: SERVER_PORT
          value: "31003"
        - name: DB_HOST
          value: "inventory-db"
        - name: DB_PORT
          value: "31009"
