apiVersion: v1
kind: Service
metadata:
  name: aggregation-service-svc
  labels:
    app: aggregation-service
spec:
  type: ClusterIP
  ports:
    - port: 31006
      targetPort: 31006
      protocol: TCP
      name: http
  selector:
    app: aggregation-service
