apiVersion: v1
kind: Service
metadata:
  name: customer-service-svc
  labels:
    app: customer-service
spec:
  type: ClusterIP
  ports:
    - port: 31001
      targetPort: 31001
      protocol: TCP
      name: http
  selector:
    app: customer-service
