apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 31003
      targetPort: 31003
      protocol: TCP
      name: http
  selector:
    app: inventory-service
