apiVersion: v1
kind: Service
metadata:
  name: search-service-svc
  labels:
    app: search-service
spec:
  type: ClusterIP
  ports:
    - port: 31005
      targetPort: 31005
      protocol: TCP
      name: http
  selector:
    app: search-service
